<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Title>UseSend FluentEmail Sender</Title>
        <Authors>Christian Schou Køster</Authors>
        <Copyright>Copyright © Christian Schou Køster</Copyright>
        <PackageProjectUrl>https://github.com/Christian-Schou/usesend-dotnet/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Christian-Schou/usesend-dotnet/</RepositoryUrl>
        <Description>FluentEmail sender backed by the useSend API.</Description>
        <PackageTags>usesend;email;fluentemail;sender</PackageTags>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <IsPackable>true</IsPackable>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentEmail.Core" Version="3.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\UseSend\UseSend.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
