<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24"/>
        <PackageReference Include="Hangfire.InMemory" Version="0.9.2"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\UseSend\UseSend.csproj"/>
    </ItemGroup>

</Project>
