<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Temporalio" Version="1.16.0" />
        <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.16.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\UseSend\UseSend.csproj"/>
    </ItemGroup>

</Project>
